default:
  context:
    parameters:
      # URL to use against the web server in the features
      url: http://localhost:8888

      # Path to the document root
      documentRoot: public

      # How many seconds will we allow the httpd to use when starting?
      timeout: 1

      # Path to the router
      router: router.php

      # Whether or not to collect code coverage
      enableCodeCoverage: true

      # Path to store the generated code coverage report
      coveragePath: build/behat-coverage

      # White list of directories to collect coverage about
      whitelist:
        - library
        - public
